### PR TITLE
Fix/frontend header

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
[Different background for the avatar picture on the user settings pages, in the user drop-down menu and in the header](https://trello.com/c/YMrvZwSe/273-different-background-for-the-avatar-picture-on-the-user-settings-pages-in-the-user-drop-down-menu-and-in-the-header)

**Comment by ghost** [comment]
[Different distances from elements to the edge of the container in the User dropdown menu](https://trello.com/c/gugmYb2b/226-different-distances-from-elements-to-the-edge-of-the-container-in-the-user-dropdown-menu)

**Comment by ghost** [comment]
[The style of the sun icon is different from the style of the rest icons in the user dropdown menu](https://trello.com/c/BOnWWE95/225-the-style-of-the-sun-icon-is-different-from-the-style-of-the-rest-icons-in-the-user-dropdown-menu)

**Comment by ghost** [comment]
[Subscribers counter text jumps upon subscription on the video page](https://trello.com/c/0dx2pjLY/243-subscribers-counter-text-jumps-upon-subscription-on-the-video-page)

**Review by Barracuda713 — APPROVED** [review]

**Pull request merged**
