### PR TITLE
Fix/frontend82 layout z index

### PR DESCRIPTION
**Pull request by Barracuda713**
This PR contains:
- add z-index config scss
- fix auth forms styles
- add link to Studio route in header

### CODE REVIEW

**Comment by Barracuda713** [comment]
[Gaps between password input fields and show/hide buttons on the Sign-up page](https://trello.com/c/mahW1VTK/105-gaps-between-password-input-fields-and-show-hide-buttons-on-the-sign-up-page)

**Comment by Barracuda713** [comment]
[Add link to the "Start stream" button in the header on the Main page](https://trello.com/c/yEV72N1V/113-add-link-to-the-start-stream-button-in-the-header-on-the-main-page)

**Comment by Barracuda713** [comment]
[The User profile dropdown menu is displayed under the search page](https://trello.com/c/vkvRSSne/82-the-user-profile-dropdown-menu-is-displayed-under-the-search-page)

**Comment by Barracuda713** [comment]
[Sign-in/Sign-up/Restore password block is missing its outline](https://trello.com/c/SIJiTb8Q/80-sign-in-sign-up-restore-password-block-is-missing-its-outline)

**Review by shirokuronemuri — APPROVED** [review]

**Pull request merged**
