### PR TITLE
Fix/profile page

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
[Implement the toaster notification about saved changes on the Profile preference page](https://trello.com/c/SlYDmV7L/176-implement-the-toaster-notification-about-saved-changes-on-the-profile-preference-page)

**Comment by ghost** [comment]
[Zoom +/- icons are similar (both are "+") on the Profile preference page](https://trello.com/c/jmMu5Xw8/172-zoom-icons-are-similar-both-are-on-the-profile-preference-page)

**Comment by ghost** [comment]
[Username changes to userID after uploading the profile picture](https://trello.com/c/u8AuIuvC/156-username-changes-to-userid-after-uploading-the-profile-picture)

**Comment by ghost** [comment]
[Fix profile page styles](https://trello.com/c/v6WRKpma/153-fix-profile-page-styles)

**Review by Barracuda713 — APPROVED** [review]

**Pull request merged**
